import {useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {getPlayer,getPlayers} from '../api/players';
import {createPlayerApplication,getMyPlayerApplications,uploadPlayerApplicationImage} from '../api/playerApplications';
import {useAsync} from '../hooks/useAsync';
import type {PlayerApplicationStatus,Position} from '../types';
import {ImageFallback,PageHeader,State} from '../components/UI';

const positions:Array<Position|''>=['','GK','DF','MF','FW'];

export function PlayersPage(){const [position,setPosition]=useState<Position|''>('');const {data,loading,error}=useAsync(()=>getPlayers(position||undefined),[position]);return <div className="container-page page-space"><PageHeader title="선수단" description="서원 FC와 함께 뛰는 선수들을 소개합니다." action={<div className="flex gap-2"><Link className="btn-secondary" to="/players/my-applications">내 신청 내역</Link><Link className="btn-primary" to="/players/apply">선수 등록 신청</Link></div>}/><div className="mb-8 flex gap-2 overflow-x-auto">{positions.map(p=><button key={p||'ALL'} onClick={()=>setPosition(p)} className={position===p?'btn-primary':'btn-secondary'}>{p||'전체'}</button>)}</div><State loading={loading} error={error} empty={!data?.content.length}><div className="grid grid-cols-2 gap-4 md:grid-cols-3 md:gap-6 lg:grid-cols-4">{data?.content.map(p=><Link className="card overflow-hidden" to={`/players/${p.id}`} key={p.id}><ImageFallback src={p.profileImageUrl||p.imageUrl} alt={p.name} className="aspect-[3/4] w-full object-cover"/><div className="p-4"><p className="text-xs text-muted">{p.position} · NO. {p.backNumber??p.number??'-'}</p><h2 className="mt-1 text-lg font-semibold">{p.name}</h2>{p.nationality&&<p className="mt-2 text-xs text-muted">{p.nationality}</p>}</div></Link>)}</div></State></div>}

export function PlayerApplicationPage(){
  const navigate=useNavigate();
  const [form,setForm]=useState({name:'',backNumber:'',position:'' as Position|'',nationality:'대한민국'});
  const [preview,setPreview]=useState('');
  const [profileImageUrl,setProfileImageUrl]=useState('');
  const [uploading,setUploading]=useState(false);
  const [error,setError]=useState('');
  const [submitting,setSubmitting]=useState(false);
  const selectFile=async(next:File|null)=>{if(preview)URL.revokeObjectURL(preview);setPreview(next?URL.createObjectURL(next):'');setProfileImageUrl('');setError('');if(!next)return;setUploading(true);try{setProfileImageUrl(await uploadPlayerApplicationImage(next))}catch(reason){setError(reason instanceof Error?reason.message:'사진을 업로드하지 못했습니다.')}finally{setUploading(false)}};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!profileImageUrl){setError(uploading?'프로필 사진을 업로드하고 있습니다.':'프로필 사진을 선택해주세요.');return}if(!form.position){setError('포지션을 선택해주세요.');return}setSubmitting(true);setError('');try{await createPlayerApplication({name:form.name.trim(),backNumber:Number(form.backNumber),position:form.position,nationality:form.nationality.trim(),profileImageUrl});alert('신청이 접수되었습니다. 관리자 승인 후 반영됩니다');navigate('/players/my-applications')}catch(reason){setError(reason instanceof Error?reason.message:'신청을 접수하지 못했습니다.')}finally{setSubmitting(false)}};
  return <div className="container-page page-space"><div className="mx-auto max-w-2xl"><PageHeader title="선수 등록 신청" description="프로필 사진은 신청 제출 전에 안전하게 업로드됩니다."/><form className="card grid gap-5 p-5 md:grid-cols-2 md:p-8" onSubmit={submit}><label><span className="label">이름 *</span><input className="field" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span className="label">등번호 *</span><input className="field" type="number" min="0" required value={form.backNumber} onChange={e=>setForm({...form,backNumber:e.target.value})}/></label><label><span className="label">포지션 *</span><select className="field" required value={form.position} onChange={e=>setForm({...form,position:e.target.value as Position})}><option value="">선택해주세요</option>{positions.slice(1).map(position=><option value={position} key={position}>{position}</option>)}</select></label><label><span className="label">국적 *</span><input className="field" required value={form.nationality} onChange={e=>setForm({...form,nationality:e.target.value})}/></label><label className="md:col-span-2"><span className="label">프로필 사진 *</span><input className="field py-2" type="file" accept="image/*" required onChange={e=>void selectFile(e.target.files?.[0]??null)}/>{uploading&&<span className="mt-2 block text-xs text-muted">사진 업로드 중...</span>}{profileImageUrl&&<span className="mt-2 block text-xs font-medium">사진 업로드 완료</span>}</label>{preview&&<img className="aspect-[3/4] w-40 rounded-lg border border-line object-cover md:col-span-2" src={preview} alt="프로필 사진 미리보기"/>}{error&&<p className="text-sm text-danger md:col-span-2">{error}</p>}<div className="flex justify-end gap-2 md:col-span-2"><Link className="btn-secondary" to="/players">취소</Link><button className="btn-primary" disabled={submitting||uploading}>{submitting?'처리 중...':uploading?'업로드 중...':'신청하기'}</button></div></form></div></div>
}

const statusLabel:Record<PlayerApplicationStatus,string>={PENDING:'대기중',APPROVED:'승인됨',REJECTED:'반려됨'};
export function MyPlayerApplicationsPage(){const applications=useAsync(getMyPlayerApplications,[]);return <div className="container-page page-space"><PageHeader title="내 선수 등록 신청" description="신청 처리 상태를 확인할 수 있습니다." action={<Link className="btn-primary" to="/players/apply">새 신청</Link>}/><State loading={applications.loading} error={applications.error} empty={!applications.data?.length} emptyMessage="아직 신청 내역이 없습니다."><div className="grid gap-4 md:grid-cols-2">{applications.data?.map(item=><article className="card flex gap-4 p-5" key={item.id}><ImageFallback src={item.profileImageUrl} alt={item.name} className="h-28 w-20 shrink-0 rounded object-cover"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-semibold">{item.name}</h2><StatusBadge status={item.status}/></div><p className="mt-2 text-sm text-muted">{item.position} · 등번호 {item.backNumber} · {item.nationality}</p>{item.status==='REJECTED'&&item.rejectReason&&<p className="mt-4 border-l-2 border-danger pl-3 text-sm text-danger">반려 사유: {item.rejectReason}</p>}</div></article>)}</div></State></div>}

function StatusBadge({status}:{status:PlayerApplicationStatus}){const style=status==='APPROVED'?'border-ink bg-ink text-white':status==='REJECTED'?'border-danger font-semibold text-danger':'border-line bg-surface text-muted';return <span className={`shrink-0 rounded-full border px-3 py-1 text-xs ${style}`}>{statusLabel[status]}</span>}

export function PlayerDetailPage(){const {id=''}=useParams();const {data,loading,error}=useAsync(()=>getPlayer(id),[id]);return <div className="container-page page-space"><State loading={loading} error={error} empty={!data}>{data&&<div className="mx-auto grid max-w-4xl gap-8 md:grid-cols-2"><ImageFallback src={data.profileImageUrl||data.imageUrl} alt={data.name} className="aspect-[3/4] w-full rounded-lg object-cover"/><div className="py-4"><p className="text-sm font-medium">{data.position} · NO. {data.backNumber??data.number??'-'}</p><h1 className="mt-3 text-4xl font-bold">{data.name}</h1><dl className="mt-10 divide-y divide-line border-y border-line">{[['국적',data.nationality],['생년월일',data.birth||data.birthDate],['신장',data.height&&`${data.height}cm`],['체중',data.weight&&`${data.weight}kg`]].map(([k,v])=><div className="flex py-4" key={String(k)}><dt className="w-28 text-sm text-muted">{k}</dt><dd>{v||'-'}</dd></div>)}</dl>{data.stats&&Object.keys(data.stats).length>0&&<section className="mt-8"><h2 className="text-xl font-semibold">시즌 기록</h2><dl className="mt-4 grid grid-cols-2 gap-px overflow-hidden rounded border border-line bg-line">{Object.entries(data.stats).map(([key,value])=><div className="bg-white p-4" key={key}><dt className="text-xs text-muted">{statLabel(key)}</dt><dd className="mt-1 text-xl font-bold">{value??'-'}</dd></div>)}</dl></section>}{data.introduction&&<p className="mt-8 whitespace-pre-wrap leading-7">{data.introduction}</p>}</div></div>}</State></div>}

const statLabel=(key:string)=>({appearances:'출전',goals:'득점',assists:'도움',yellowCards:'경고',redCards:'퇴장'}[key]??key);
